# derived from 
#<https://github.com/marketplace/actions/mkdocs-action>
#<https://gist.github.com/liflovs/f2a950dadcca25a0dbdfe10f53f5c838>
#<https://stackoverflow.com/questions/64374179/how-to-push-to-another-repository-in-github-actions>
#<https://stackoverflow.com/questions/41714882/git-how-to-clone-with-ssh-key-username>

name: mkdocs-build

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create virtualenv and install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          # Option 1: install from requirements.txt (recommended only after you confirm pins)
          pip install -r requirements.txt
          # OR Option 2: explicit install (ensures consistent ordering)
          # pip install mkdocs==1.5.3 mkdocs-material==9.5.18 mkdocs-rss-plugin==1.17.4

      - name: Build site
        run: |
          . .venv/bin/activate
          mkdocs build -f mkdocs.yml -d site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          allow_empty_commit: true
